apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-agent-sa
  namespace: default
  annotations:
    # This connects the K8s Service Account to the Azure Identity
    azure.workload.identity/client-id: "8f9cae76-2daa-426b-88f5-6e062aee5896"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-agent-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-agent
  template:
    metadata:
      labels:
        app: ai-agent
        # This triggers the injection of the Workload Identity tokens
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: ai-agent-sa
      containers:
      - name: ai-agent
        image: demoacr.azurecr.io/passwordless-ai-ops-app:v8
        env:        
        - name: USE_MANAGED_IDENTITY
          value: "true"
        - name: STORAGE_ACCOUNT_URL
          value: "https://mygenaiusecases.blob.core.windows.net/"
        - name: AZURE_OPENAI_ENDPOINT
          value: "https://vijay-mkiemtgq-swedencentral.cognitiveservices.azure.com/"
        - name: AZURE_OPENAI_DEPLOYMENT_NAME
          value: "gpt-5.2-chat"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: ai-agent-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: ai-agent